In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a = np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
a1 = np.random.randint(3,4)
a2 = np.random.choice(3,4)
a3 = np.random.rand(3,4)


print(a1)
print(a2)
print(a3)


3
[2 2 0 1]
[[0.11381639 0.64747093 0.74966713 0.58690178]
 [0.34796283 0.63645653 0.80879565 0.07723092]
 [0.15657194 0.13958367 0.12200772 0.04416737]]


In [9]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr = np.reshape(arr,(2,5))
print(arr.shape)

(2, 5)


In [12]:
arr = np.array([
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11],
    [12,13,14,15]
])

axis = np.array([True,False,False,False])
print(arr[axis])

[[0 1 2 3]]


In [13]:
import pandas as pd

data = {
    'year': [2016, 2017, 2018],
    'GDP rate': [2.8, 3.1, 3.0],
    'GDP': ['1.637M', '1.73M', '1.83M']
    
}

df = pd.DataFrame(data, index = data['year'])
print(df)

      year  GDP rate     GDP
2016  2016       2.8  1.637M
2017  2017       3.1   1.73M
2018  2018       3.0   1.83M
